"use client";

import { Download, Share2 } from "lucide-react";
import type { SnippetMetadata, SnippetRecord } from "@/src/types/snippets";

interface ExportCenterProps {
  snippets: SnippetRecord[];
}

function downloadBlob(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export default function ExportCenter({ snippets }: ExportCenterProps) {
  const latest = snippets[0] ?? null;
  const latestMetadata = (latest?.metadata_json ?? {}) as Partial<SnippetMetadata>;

  async function copyLatest() {
    if (!latest) return;
    const sourceName = latestMetadata.attributionFileName ?? "Unknown source";
    const header = `// Generated by Synthetix from ${sourceName}`;
    await navigator.clipboard.writeText(`${header}\n\n${latest.code_body}`);
  }

  async function downloadLatest() {
    if (!latest) return;
    const res = await fetch(`/api/snippets/${latest.id}/export`);
    if (!res.ok) {
      const sourceName = latestMetadata.attributionFileName ?? "Unknown source";
      const fallback = `// Generated by Synthetix from ${sourceName}\n\n${latest.code_body}`;
      const ext = latestMetadata.language === "micropython" ? "py" : "ino";
      downloadBlob(`${latest.snippet_name}.${ext}`, fallback);
      return;
    }
    const payload = await res.text();
    const ext = latestMetadata.language === "micropython" ? "py" : "ino";
    downloadBlob(`${latest.snippet_name}.${ext}`, payload);
  }

  return (
    <div className="flex items-center gap-2">
      <button
        type="button"
        onClick={copyLatest}
        disabled={latest === null}
        className="flex items-center gap-2 rounded-lg border border-black/[0.08] bg-gray-50 px-4 py-2 text-sm font-semibold text-[#111] transition-colors hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-60"
      >
        <Share2 className="h-4 w-4" />
        Copy Latest
      </button>
      <button
        type="button"
        onClick={downloadLatest}
        disabled={latest === null}
        className="flex items-center gap-2 rounded-lg bg-[var(--v2-primary)] px-4 py-2 text-sm font-bold text-white shadow-md shadow-[var(--v2-primary)]/20 transition-colors hover:bg-[#0278e0] disabled:cursor-not-allowed disabled:opacity-60"
      >
        <Download className="h-4 w-4" />
        Download Latest
      </button>
    </div>
  );
}
