"use client";

import { ChevronDown, ChevronRight, Copy, Download, Trash2 } from "lucide-react";
import { useLayoutEffect, useState } from "react";
import type { SnippetMetadata, SnippetRecord } from "@/src/types/snippets";

interface SnippetCardProps {
  snippet: SnippetRecord;
  onDelete: (snippetId: string) => Promise<void>;
}

function downloadBlob(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

const SNIPPET_COLLAPSED_KEY = "synthetix:snippet-collapsed:v1";

function readSnippetCollapsed(snippetId: string): boolean {
  if (typeof window === "undefined") return false;
  try {
    const raw = window.localStorage.getItem(SNIPPET_COLLAPSED_KEY);
    if (!raw) return false;
    const map = JSON.parse(raw) as Record<string, boolean>;
    return map[snippetId] === true;
  } catch {
    return false;
  }
}

function persistSnippetCollapsed(snippetId: string, collapsed: boolean): void {
  if (typeof window === "undefined") return;
  try {
    const raw = window.localStorage.getItem(SNIPPET_COLLAPSED_KEY);
    const map = raw ? (JSON.parse(raw) as Record<string, boolean>) : {};
    if (collapsed) {
      map[snippetId] = true;
    } else {
      delete map[snippetId];
    }
    window.localStorage.setItem(SNIPPET_COLLAPSED_KEY, JSON.stringify(map));
  } catch {
    // ignore quota / parse errors
  }
}

export default function SnippetCard({ snippet, onDelete }: SnippetCardProps) {
  const [deleting, setDeleting] = useState(false);
  /** Start expanded on first paint so SSR and client match; then restore from storage. */
  const [collapsed, setCollapsed] = useState(false);

  useLayoutEffect(() => {
    setCollapsed(readSnippetCollapsed(snippet.id));
  }, [snippet.id]);
  const metadata = (snippet.metadata_json ?? {}) as Partial<SnippetMetadata>;
  const language = metadata.language ?? "cpp";
  const dependency = metadata.dependency ?? "Unknown";
  const interfaceName = metadata.interface ?? "Unknown";
  const targetHw = metadata.targetHw ?? "esp32";
  const attributionFileName = metadata.attributionFileName ?? "Unknown source";
  const extension = metadata.language === "micropython" ? "py" : "ino";
  const attributionHeader = `// Generated by Synthetix from ${attributionFileName}`;

  async function handleCopy() {
    const payload = `${attributionHeader}\n\n${snippet.code_body}`;
    await navigator.clipboard.writeText(payload);
  }

  async function handleDownload() {
    const res = await fetch(`/api/snippets/${snippet.id}/export`);
    if (!res.ok) {
      const fallback = `${attributionHeader}\n\n${snippet.code_body}`;
      downloadBlob(`${snippet.snippet_name}.${language === "micropython" ? "py" : "ino"}`, fallback);
      return;
    }
    const text = await res.text();
    downloadBlob(`${snippet.snippet_name}.${extension}`, text);
  }

  async function handleDelete() {
    if (deleting) return;
    if (!window.confirm("Delete this snippet?")) return;
    setDeleting(true);
    try {
      await onDelete(snippet.id);
    } finally {
      setDeleting(false);
    }
  }

  return (
    <div className="flex flex-col overflow-hidden rounded-xl border border-white/10">
      <div className="flex items-center justify-between bg-[#1a1a1a] px-4 py-3">
        <div className="flex items-center gap-2">
          <span className="h-3 w-3 rounded-full bg-red-500/60" />
          <span className="h-3 w-3 rounded-full bg-yellow-500/60" />
          <span className="h-3 w-3 rounded-full bg-green-500/60" />
          <span className="ml-3 font-mono text-[11px] font-bold uppercase tracking-widest text-zinc-500">
            {snippet.snippet_name}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            title={collapsed ? "Expand snippet" : "Collapse snippet"}
            onClick={() => {
              setCollapsed((prev) => {
                const next = !prev;
                persistSnippetCollapsed(snippet.id, next);
                return next;
              });
            }}
            className="text-zinc-500 transition-colors hover:text-white"
          >
            {collapsed ? (
              <ChevronRight className="h-4 w-4" />
            ) : (
              <ChevronDown className="h-4 w-4" />
            )}
          </button>
          <button
            type="button"
            title="Copy with attribution"
            onClick={handleCopy}
            className="text-zinc-500 transition-colors hover:text-white"
          >
            <Copy className="h-4 w-4" />
          </button>
          <button
            type="button"
            title="Delete snippet"
            onClick={handleDelete}
            disabled={deleting}
            className="text-zinc-500 transition-colors hover:text-red-400 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Trash2 className="h-4 w-4" />
          </button>
          <button
            type="button"
            title="Download snippet file"
            onClick={handleDownload}
            className="text-zinc-500 transition-colors hover:text-white"
          >
            <Download className="h-4 w-4" />
          </button>
        </div>
      </div>

      {!collapsed ? (
        <div className="flex-1 bg-[#1a1a1a] px-6 py-5">
          <pre className="overflow-x-auto font-mono text-xs leading-relaxed text-zinc-300">
            <code>{snippet.code_body}</code>
          </pre>
        </div>
      ) : null}

      <div className="flex flex-wrap items-center gap-2 border-t border-white/[0.06] bg-[#141414] px-4 py-2.5">
        <div className="flex flex-wrap gap-1.5">
          <span className="rounded bg-zinc-800 px-2 py-0.5 text-[9px] font-bold uppercase text-zinc-400">
            {dependency}
          </span>
          <span className="rounded bg-zinc-800 px-2 py-0.5 text-[9px] font-bold uppercase text-zinc-400">
            {interfaceName}
          </span>
          <span className="rounded bg-zinc-800 px-2 py-0.5 text-[9px] font-bold uppercase text-zinc-400">
            {targetHw}
          </span>
        </div>
      </div>
    </div>
  );
}
