import { NextRequest, NextResponse } from "next/server";
import { createServerSupabase } from "@/src/lib/supabase/server";
import type { SnippetMetadata } from "@/src/types/snippets";

export const runtime = "nodejs";

function extensionFromMetadata(metadata: SnippetMetadata): string {
  return metadata.language === "micropython" ? "py" : "ino";
}

export async function GET(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const supabase = await createServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await context.params;
  if (!id) {
    return NextResponse.json({ error: "Missing snippet id" }, { status: 400 });
  }

  try {
    const { data: snippet, error: snippetError } = await supabase
      .from("snippets")
      .select("id, snippet_name, code_body, metadata_json")
      .eq("id", id)
      .eq("user_id", user.id)
      .maybeSingle();

    if (snippetError) {
      throw new Error(`Failed to load snippet: ${snippetError.message}`);
    }
    if (!snippet) {
      return NextResponse.json({ error: "Snippet not found" }, { status: 404 });
    }

    const metadata = snippet.metadata_json as SnippetMetadata;
    const attribution = `// Generated by Synthetix from ${metadata.attributionFileName}`;
    const exportBody = `${attribution}\n\n${snippet.code_body}`;
    const fileExt = extensionFromMetadata(metadata);
    const fileName = `${snippet.snippet_name}.${fileExt}`;

    return new Response(exportBody, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown export error";
    console.error("[/api/snippets/[id]/export]", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
